---
project_onboarding_name: helios
project_onboarding_group: "{{ project_onboarding_name }}"
project_onboarding_qos: "project-{{ project_onboarding_name }}"
project_onboarding_storage_path: "/shared/projects/{{ project_onboarding_name }}"
project_onboarding_password: DemoPass123!
project_onboarding_users:
  - username: alice_helios
    first_name: Alice
    last_name: Helios
    email: alice_helios@demo.lab
  - username: bob_helios
    first_name: Bob
    last_name: Helios
    email: bob_helios@demo.lab
