---
galaxy_info:
  role_name: cm_fips_mode
  author: rcd-cui
  description: "CM control role for CUI compliance"
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "9"
dependencies:
  - role: common
