---
# WHY: Restart managed services only when configuration has changed.
- name: Restart au_chrony services
  ansible.builtin.systemd:
    name: "{{ item.name }}"
    state: restarted
  loop: "{{ au_chrony_services }}"
  when: au_chrony_services | length > 0
  listen: Restart au_chrony services
  tags:
    - r2_3.3.7
    - r3_03.03.07
    - family_AU
    - zone_{{ cui_zone }}
