---
# WHY: Restart managed services only when configuration has changed.
- name: Restart cm_minimal_packages services
  ansible.builtin.systemd:
    name: "{{ item.name }}"
    state: restarted
  loop: "{{ cm_minimal_packages_services }}"
  when: cm_minimal_packages_services | length > 0
  listen: Restart cm_minimal_packages services
  tags:
    - r2_3.4.6
    - r3_03.04.06
    - family_CM
    - zone_{{ cui_zone }}
